import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Table } from 'antd'
import { columns, data } from '../data/table.js'
import 'antd/dist/antd.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CassyYu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table columns={columns} dataSource={data} pagination={false}/>
    </div>
  )
}


export default Home
